name: Publish Static Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install
        working-directory: ./blog

      - run: bun run build.client && bun run build.server
        working-directory: ./blog

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./blog/dist
          cname: hogpit.muehl.dev

